local LOCATION_DATA             = {
  ["Anchorage"] = {
    pos = { -1.082, 0.11 , -0.568 },
    page = 55,
    orientation = "left"
  },
  ["San Francisco"] = {
    pos = { -1.041, 0.11 , -0.364 },
    page = 47,
    orientation = "left"
  },
  ["Ybor City"] = {
    pos = { -0.76, 0.11 , -0.253 },
    page = 74,
    orientation = "left"
  },
  ["Havana]"] = {
    pos = { -0.754, 0.11 , -0.205 },
    page = 50,
    orientation = "left"
  },
  ["Bermuda"] = {
    pos = { -0.581, 0.11 , -0.305 },
    page = 41,
    orientation = "right"
  },
  ["Buenos Aires"] = {
    pos = { -0.551, 0.11 , 0.356 },
    page = 37,
    orientation = "left"
  },
  ["Rio de Janeiro"] = {
    pos = { -0.438, 0.11 , 0.232 },
    page = 66,
    orientation = "left"
  },
  ["Marrakesh"] = {
    pos = { -0.144, 0.11 , -0.296 },
    page = 32,
    orientation = "right"
  },
  ["Alexandria"] = {
    pos = { 0.16, 0.11 , -0.298 },
    page = 60,
    orientation = "right"
  },
  ["Rome"] = {
    pos = { 0.03, 0.11 , -0.387 },
    page = 73,
    orientation = "right"
  },
  ["Stockholm"] = {
    pos = { 0.049, 0.11 , -0.562 },
    page = 58,
    orientation = "left"
  },
  ["Moscow"] = {
    pos = { 0.204, 0.11 , -0.533 },
    page = 47,
    orientation = "right"
  },
  ["Constantinople"] = {
    pos = { 0.144, 0.11 , -0.387 },
    page = 42,
    orientation = "right"
  },
  ["Lagos"] = {
    pos = { -0.054, 0.11 , -0.048 },
    page = 59,
    orientation = "right"
  },
  ["Nairobi"] = {
    pos = { 0.216, 0.11 , 0.021 },
    page = 79,
    orientation = "left"
  },
  ["Bombay"] = {
    pos = { 0.522, 0.11 , -0.171 },
    page = 58,
    orientation = "right"
  },
  ["Kathmandu"] = {
    pos = { 0.623, 0.11 , -0.242 },
    page = 76,
    orientation = "right"
  },
  ["Shanghai"] = {
    pos = { 0.894, 0.11 , -0.289 },
    page = 54,
    orientation = "left"
  },
  ["Tokyo"] = {
    pos = { 0.991, 0.11 , -0.354 },
    page = 59,
    orientation = "right"
  },
  ["Perth"] = {
    pos = { 0.852, 0.11 , 0.323 },
    page = 80,
    orientation = "right"
  },
  ["Sydney"] = {
    pos = { 1.123, 0.11 , 0.338 },
    page = 71,
    orientation = "left"
  },

  -- bonus locations
  ["Reykjavik"] = {
    pos = { -0.201, 0.11 , -0.598 },
    page = 35,
    orientation = "right"
  },
  ["Tunguska"] = {
    pos = { 0.674, 0.11 , -0.562 },
    page = 84,
    orientation = "right"
  },
  ["Kabul"] = {
    pos = { 0.478, 0.11 , -0.333 },
    page = 35,
    orientation = "right"
  },
  ["Kuala Lumpur"] = {
    pos = { 0.775, 0.11 , -0.018 },
    page = 68,
    orientation = "right"
  },
  ["Hong Kong"] = {
    pos = { 0.855, 0.11 , -0.204 },
    page = 72,
    orientation = "left"
  },
  ["Manokwari"] = {
    pos = { 1.044, 0.11 , 0.022 },
    page = 67,
    orientation = "left"
  },
  ["San Juan"] = {
    pos = { -0.63, 0.11 , -0.167 },
    page = 35,
    orientation = "right"
  },
  ["Quito"] = {
    pos = { -0.748, 0.11 , 0.012 },
    page = 35,
    orientation = "right"
  },
  ["Amazonia"] = {
    pos = { -0.619, 0.11 , 0.041 },
    page = 134,
    orientation = "right"
	},
  ["Arkham"] = {
    pos = { -0.628, 0.11 , -0.394 },
    page = 96,
    orientation = "right"
	},
  ["New Orleans"] = {
    pos = { -0.808, 0.11 , -0.291 },
    page = 107,
    orientation = "right"
	},
  ["Antarctica"] = {
    pos = { -0.12, 0.11 , 0.692 },
    page = 157,
    orientation = "right"
	},
  ["London"] = {
    pos = { -0.077, 0.11 , -0.49 },
    page = 49,
    orientation = "left"
	},
  ["Kingsport"] = {
    pos = { -0.611, 0.11 , -0.43 },
    page = 116,
    orientation = "left"
	},
  ["Paris"] = {
    pos = { -0.042, 0.11 , -0.457 },
    page = 145,
    orientation = "right"
	},
  ["Venice"] = {
    pos = { 0.023, 0.11 , -0.43 },
    page = 126,
    orientation = "right"
	},
  ["Monte Carlo"] = {
    pos = { -0.025, 0.11 , -0.413 },
    page = 120,
    orientation = "left"
	},
  ["Cairo"] = {
    pos = { 0.165, 0.11 , -0.263 },
    page = 111,
    orientation = "left"
	},
  ["Los Angeles"] = {
    pos = { -1.017, 0.11 , -0.314 },
    page = 150,
    orientation = "left"
  }
}

local buttonParameters          = {}
buttonParameters.function_owner = self
buttonParameters.label          = ""
buttonParameters.color          = { 0, 0, 0, 0 }
buttonParameters.width          = 900
buttonParameters.height         = 200
buttonParameters.scale          = { 0.1, 0.1, 0.1 }

function onLoad()
  for name, data in pairs(LOCATION_DATA) do
    pageButton(name, data)
  end
end

-- helper functions to carry page
function attachPage(click_function, page)
  local fn_name = click_function .. page
  _G[fn_name] = function(_, playerColor, isRightClick)
    goToPage(playerColor, page)
  end
  return fn_name
end

function pageButton(name, data)
  local offset = 0.08

  if data.orientation == "left" then
    data.pos[1] = data.pos[1] - offset
  else
    data.pos[1] = data.pos[1] + offset
  end

  buttonParameters.tooltip = "open page (" .. name .. ")"
  buttonParameters.position = data.pos
  buttonParameters.click_function = attachPage("buttonClick", data.page)
  self.createButton(buttonParameters)
end

function goToPage(playerColor, page)
  local campaignGuide = getObjectsWithTag("CampaignGuide")
  if #campaignGuide == 0 then
    printToColor("Couldn't find campaign guide. Make sure it is tagged with 'CampaignGuide'.", playerColor)
    return
  end
  campaignGuide[1].Book.setPage(page - 1)
end
